apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kube.name }}
  labels:
    app: {{ .Values.kube.name }}
spec:
  replicas: {{ .Values.kube.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kube.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kube.name }}
    spec:
      containers:
      - name: {{ .Values.kube.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          {{- toYaml .Values.env | nindent 10 }}
        ports:
        - containerPort: {{ .Values.image.containerPort }}
