apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kube.name }}
  labels:
    app: {{ .Values.kube.name }}
spec:
  type: NodePort
  ports:
  - port: 8100
    targetPort: {{ .Values.image.containerPort }}
    nodePort: {{ .Values.kube.port }}
  selector:
    app: {{ .Values.kube.name }}